# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Untaint-asin
version:      1.01
version_from: lib/CGI/Untaint/asin.pm
installdirs:  site
requires:
    CGI::Untaint:                  0.07
    Test::CGI::Untaint:            1.1
    Test::More:                    0.11

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
